markdown: rdiscount                 
permalink: /:year/:month/:day/:title/
url: http://williamlfang.github.com/cn
author: William Fang
pygments: true
auto: true
safe: true
paginate: 10

web: williamlfang.github.com
qq: 564985882
email: william.lian.fang@gmail.com
duoshuo: 夏石
weibo: 夏石_will
github: williamlfang

