markdown: kramdown
permalink: /:year/:month/:day/:title/
url: http://williamlfang.github.com/cn
author: William Fang
pygments: true
auto: true
safe: true
paginate: 15
future: false
timezone: Asia/Shanghai

web: williamlfang.github.com
qq: 564985882
email: william.lian.fang@gmail.com
duoshuo: 夏石
weibo: 夏石_will
github: williamlfang

title : 方莲 | William
keywords: "宏观经济，利率理论，金融理论与资产定价，统计与计量经济学，R语言，新型经济与互联网"
description : "人生就像那旅程,谁知道转弯后的风光"

author :
  name : william
  email : william.lian.fang@gmail.com
  github : williamlfang
  twitter : 564985882@qq.com

JB :
  version : 0.3.0
  BASE_PATH : false
  ASSET_PATH : false
  archive_path: /archives.html
  about_path: /about.html
  links_path: /links.html
  tags_path : /tags.html
  atom_path : /atom.xml
  rss_path : /rss.xml
  sitemap_path : /sitemap.xml
  search_path : /search.html
  guestbook_path : /guestbook.html


