markdown: rdiscount
permalink: /:year/:month/:title/
url: http://williamlfang.github.com/cn
author: William Fang
pygments: true


qq: 564985882
email: william.lian.fang@gmail.com
duoshuo: 夏石
weibo: 夏石_will
github: williamlfang
pygments: true
safe: true
