---
layout:   post
title:    "ggplot2入门之qplot"
category:  R
tags:     
- R 
- ggplot2
- qplot
description: 
published: false
status:    process
---

据说 `R` 中那些优秀的扩展包（packages）都可以独立成一个新的统计软件，成为独霸一方的「草莽大王」，都值得我们为此「大书特书」一番。比如，时下我们会深入介绍的这款专门由于制作漂亮而不失矜持、俏丽而不失内涵、简单而不失充实的扩展包 -- `ggplot2`。然而，如果你只是把我们今天的主角简单的看作是一款为数据画图的工具的话，那么这就有失偏颇了。乍一看，似乎我们传统的思维是把数据的可（zuo）视（tu）化（xing）仅仅作为统计分析的一个附属品，权做为说明而做的图形展现。这就好比是一场豪华婚礼中只能配得的「伴娘」，虽然自身也是穿衣戴宝的，却始终不能为大家器重。不知大家有没有想过，如果我们可以同时把数据的统计分析结果与数据直观特征图形结合在一起，通过这两者的交互印证，使得分析的结果更加具有说服力。说的更加直白一些，往往有些数据的特征是无法使用自然或者数理语言简明扼要的说清楚的，这时候就需要图形化的展示来提供更加充足的信息。也就是说，利用对数据制作「量体裁衣」的可视化展现，可以为我们的提供更加全面的信息，也在一定程度上为后期的数据统计分析提供直观的印象。

<!-- more -->

## 数据可视化的基本思想

`ggplot2` 能够使用简单的语法将数据的属性特征以图形可视化的形式展示出来，丰富了我们对数据的直观影响。不过，需要注意的，`ggplot2` 只是提供了一套静态的图形输出，尤其是适合与 PDF 格式的文件。但在现在互联网与移动屏的可视化时代，难免显得有点力不从心，无法满足我们对交互式图形的诉求。因此， Rstudio 公司后来在 Xie Yihui 同学的领导下，开发了适合与显示器屏幕的动态交互式图形输出包—— `Shiny`，以满足互联网移动屏幕的新要求。这个我们在今后介绍如何使用 \R 开发网页时再具体介绍。

因此，Hadley 一上来就开宗明义的「提醒」大家不要仅仅把  `ggplot2` 当作是一个绘图工具而已：

     `ggplot2` is a `R` package for producing statistical, or data, graphics, **but it is unlike most other graphics packages because it has a deep underlying grammer**.

这里所说的图形的「语法」（grammer），最早由 Wilkinson 提出，大体的思想是把一个数据图形看作由描述数据不同特征的属性所构成的套装，通过对不同组件的选择，来达到想要（甚至是想不到）的套装效果。这其中，不同的属性组件包括了：

 - 数据：通常要求数据结构是 `data.frame`。所谓的「裸数据」，就是未经任何修改的原始数据。
 - 几何对象：`geom` , 希望以直观的几何图形来显示数据特征，如点、线条等。
 - 统计转换：`stat`,以数据统计分析的结果展示在图形中，这比传统的将统计输出单独展现具有更加直观的认识。
 - scales：
 - 坐标系统：`coord`, 描述了如何将数据通过多维图形展现出来。
 - 分页展示：`facet`,  就是把不同组别的数据通过分页的形式表示出来，这相当于做了一次 subsetting 的分组。

## 用法说明

下面，我们来具体看看如何使用 `qplot` 绘制精美的数据可视化图形。
`qplot` 的基本用法和 `plot` 大体类似。主要的参数输入有：

- 数据：主要是使用 $x$ 和 $y$ 作为两个坐标轴，并且指定数据框类数据 \rcode{data}；
- 图形修饰：这个主要是通过 \rcode{aesthetics} 参数来完成，包括了
  + `color`：使用不同的颜色来区分数据
  + `size`：利用形状来区分数据
  + `fill`：主要是在进行 `histogram` 和 `density` 的时候用于填充不同的数据，使得各种数据的比例更加直观明显。
- 几何形状方面：利用 `geom` 来控制输出的图形几何形状，包括了
  + `geom = "point"`：作为默认设置，以点的形式画图；
  + `geom = "line"`：以线条的样子输出，通常适用于**时间序列数据**；
  + `geom = "smooth"`：使用统计拟合输出；
   > `geom = "path"`：与时间序列类似，但是按照数据的先后顺序输出；
   > `geom = "boxplot"`：输出传统统计学角度的「箱叶图」，以五个**quantile** 作标记；
   > `geom = "jitter"`：类似于「箱叶图」，但是更加突出数据的分散描述，可以使用 `alpha = I ()` 来控制分散的透明程度；
   > `geom = "histogram"`：柱状图，可以使用参数 `binwidth` 来控制间隔大小；
   > `geom = "density"`：概率分布图；
  
  我们可以通过使用 `help(qplot)` 命令来查看其基本的函数结构：
```{r eval=FALSE}
qplot(x, y = NULL, ..., data, facets = NULL, margins = FALSE,
  geom = "auto", stat = list(NULL), position = list(NULL), xlim = c(NA,
  NA), ylim = c(NA, NA), log = "", main = NULL,
  xlab = deparse(substitute(x)), ylab = deparse(substitute(y)), asp = NA)
```
